// Code generated by MockGen. DO NOT EDIT.
// Source: internal\service\todo\verify_get_todo.go

// Package todo is a generated GoMock package.
package todo

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	todo "github.com/mi-01-24fu/go-todo-backend/internal/infrastructure/todo"
)

// MockVerifyGetTODOList is a mock of VerifyGetTODOList interface.
type MockVerifyGetTODOList struct {
	ctrl     *gomock.Controller
	recorder *MockVerifyGetTODOListMockRecorder
}

// MockVerifyGetTODOListMockRecorder is the mock recorder for MockVerifyGetTODOList.
type MockVerifyGetTODOListMockRecorder struct {
	mock *MockVerifyGetTODOList
}

// NewMockVerifyGetTODOList creates a new mock instance.
func NewMockVerifyGetTODOList(ctrl *gomock.Controller) *MockVerifyGetTODOList {
	mock := &MockVerifyGetTODOList{ctrl: ctrl}
	mock.recorder = &MockVerifyGetTODOListMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerifyGetTODOList) EXPECT() *MockVerifyGetTODOListMockRecorder {
	return m.recorder
}

// GetTODOList mocks base method.
func (m *MockVerifyGetTODOList) GetTODOList(arg0 todo.GetTODORequest) (todo.GetTODOList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTODOList", arg0)
	ret0, _ := ret[0].(todo.GetTODOList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTODOList indicates an expected call of GetTODOList.
func (mr *MockVerifyGetTODOListMockRecorder) GetTODOList(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTODOList", reflect.TypeOf((*MockVerifyGetTODOList)(nil).GetTODOList), arg0)
}
